# Generated by Django 2.1.2 on 2018-10-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytmdatabase',
            name='checksumhash',
            field=models.CharField(default='h', max_length=255),
            preserve_default=False,
        ),
    ]
