# Generated by Django 2.1.2 on 2018-10-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0002_paytmdatabase_checksumhash'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytmdatabase',
            name='txn_id',
            field=models.CharField(default='dsfadsf', max_length=100),
            preserve_default=False,
        ),
    ]
