# Generated by Django 2.1.2 on 2018-10-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0003_paytmdatabase_txn_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaytmRefundDataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField()),
                ('checksumhash', models.CharField(max_length=255)),
            ],
        ),
    ]
