# Generated by Django 2.1.2 on 2018-10-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0004_paytmrefunddatabase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaytmRefundDataBase',
        ),
    ]
