# Generated by Django 2.1.2 on 2018-10-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0005_delete_paytmrefunddatabase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmdatabase',
            name='order_id',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
