# Generated by Django 2.1.2 on 2018-10-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0006_auto_20181002_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytmdatabase',
            name='order_id',
        ),
    ]
