# Generated by Django 2.1.2 on 2018-10-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paytm', '0007_remove_paytmdatabase_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytmdatabase',
            name='order_id',
            field=models.CharField(default=2, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
